[package]
name = "spicy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
clap = { version = "*", features = ["derive"] }
# gltf = "1.4.1"
serde_json = "1.0.117"
